server:
  port: 8082

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
        pool:
          type: ELASTIC
          max-connections: 500
          acquire-timeout: 5000        # 5 сек на получение соединения
          max-idle-time: 30s          # Закрывать неактивные соединения
          max-life-time: 60s           # Максимальное время жизни соединения
      
      routes:
        - id: direct_redirect_route
          uri: http://localhost:8081
          predicates:
            - Path=/{shortcode}
          filters:
            - SetPath=/redirect-api/{shortcode}
            - name: Retry
              args:
                retries: 2
                statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
                methods: GET,POST
                backoff:
                  firstBackoff: 100ms
                  maxBackoff: 500ms
                  factor: 2
        - id: redirect_route
          uri: http://localhost:8081
          predicates:
            - Path=/redirect-api/{shortcode}
        - id: core_api_route
          uri: http://localhost:8080/
          predicates:
            - Path=/core-api/**
        - id: internal_api_route
          uri: http://localhost:8080
          predicates:
            - Path=/internal/**
          filters:
            - StripPrefix=1

  data:
    redis:
      url: redis://localhost:6379
      timeout: 2000ms
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
        shutdown-timeout: 100ms

  webflux:
    base-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:

logging:
  level:
    com.example.api_gateway: debug
    org.springframework.cloud.gateway: debug
    reactor.netty: ERROR
    org.springframework.web.reactive: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

gateway:
  core-service:
    base-url: http://localhost:8080
  redirect-service:
    base-url: http://localhost:8081
  cache:
    policy-ttl-hours: 24
  auth:
    api-key-endpoint: ${API_KEY_VALIDATION_ENDPOINT:http://auth-service:8083/api/v1/validate-key}
    sso-endpoint: ${SSO_VALIDATION_ENDPOINT:http://auth-service:8083/api/v1/validate-sso}
