server:
  port: 8081

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: DEBUG