server:
  port: 8081

spring:
  data:
    redis:
      host: localhost
      port: 6379

  main:
    web-application-type: reactive

logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: DEBUG