server:
  port: 8080

spring:
  application:
    name: url-shortener
  datasource:
    url: jdbc:postgresql://localhost:15432/shortener
    username: angelo
    password: shortener-password-testing
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

logging:
  level:
    web: trace